### ISSUE TITLE
Find/Build a good buoyancy plugin

### ISSUE THREAD

**Issue by jlunder00** [GU-RoboSub-Machine-Learning/Robosub_Simulation#20]
Build a plugin that can give our models buoyancy such that they'll behave as though they are floating in water. We will try to make the model be as close as possible to the same as the real sub in terms of the depth at which it is neutrally buoyant. Can try to borrow elements from https://gitlab.com/PalouseRobosub/Software/robosub_simulator/-/tree/master, especially their buoyancy improved plugin. NOTE: MUCH OF THEIR CODE IS NOT DIRECTLY COMPATIBLE. If borrowing ideas/structure from their format, it needs to be converted to work with our version of gazebo and ros, which is different from the versions they built their system on

**Comment by jlunder00** [comment]
When you add a plugin you need to make sure that the correct build path information is included in the closest CMakeLists.txt file to the plugin's files/folders, so that it will build properly, and make sure that any models that reference it do so with correct naming.

**Comment by jlunder00** [comment]
But wait: theres more: turns out Gazebo's version of the buoyancy plugin also has lift and drag and you just give the density of the liquid so we can just give the numbers for water and it works. Has to be applied to EVERY link though.

**Comment by jlunder00** [comment]
Will test before closing this issue

**Comment by wesmuehlhausen** [comment]
[Gazebo tutorial/info on buoyancy](https://gazebosim.org/tutorials?tut=hydrodynamics&cat=physics )

It seems like Gazebo's version does creates most of the parameters automatically (such as fluid density, center of volume, and volume). 

The only problem we can foresee is whether Gazebo accounts for the object having a different buoyancy at different depths. Or if that even matters.

**Comment by jlunder00** [comment]
The buitin buoyancy plugin will work. If there is a problem with hydrodynamic drag not being accounted for correctly, we can create a new plugin to do that.
